%%{init: {'theme':'neutral'}}%%
mindmap
    root((MicroProfile Architecture Philosophy))
        Simplicity
            Easy to use APIs
            Essential functionality
        Modularity
            Modular approach
            Reduced overhead
        Standards-based
            Open standards
            Compatibility
        Community-driven
            Java community participation
            Continuous evolution
        Vendor-Neutral
            Eclipse Foundation project
            Industry support
        Focus on Cloud-Native Applications
            Tailored for cloud
            Features for resilience and scalability
        Reactive Programming
            Responsive and scalable
            Handles concurrent requests
